[package]
name = "din"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
