name: test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu-latest/rust-${{ matrix.toolchain }}
    strategy:
      matrix:
        # beta to test next version of toolchain
        toolchain: [stable, beta]
    steps:
      - name: git checkout din/master
        uses: actions/checkout@v4
        with:
          submodules: true
      ##########################################################################
      # caches
      ##########################################################################
      # caching the entire toolchain (gcc, pk, and spike) under one key for now,
      # since din's access pattern is building them all in tandem under one action
      # TODO: fetch new toolchain when upstream cuts a new release.
      - name: cache riscv gnu toolchain
        id: cache-riscv-gnu-toolchain
        uses: actions/cache@v3
        with:
          path: |
            deps/
            /opt/riscv
          key: ${{ runner.os }}-/opt/riscv
      - name: cache cargo package deps
        id: cache-cargo-package-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}/rust-${{matrix.toolchain}}/cargo-${{ hashFiles('**/Cargo.lock') }}
      ##########################################################################
      # builds
      ##########################################################################
      - if: ${{ steps.cache-riscv-gnu-toolchain.outputs.cache-hit != 'true' }}
        name: build riscv gnu toolchain with glibc
        run: |
          mkdir -p deps
          git clone https://github.com/riscv/riscv-gnu-toolchain deps/riscv-gnu-toolchain
          sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
          cd deps/riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv --with-arch=rv32gc --with-abi=ilp32d
          make linux

          mkdir build-pk
          cd build-pk
          ../configure --prefix=/opt/riscv --host=riscv32-unknown-elf
          make
          make install

          cd ../
          sudo apt-get install device-tree-compiler libboost-regex-dev
          mkdir build-spike
          cd build-spike
          ../configure --prefix=/opt/riscv --with-arch=rv32gc --with-abi=ilp32d
          make
      - if: ${{ steps.cache-cargo-package-deps.outputs.cache-hit != 'true' }}
        name: build din with release profile
        run: cargo build --release
      - name: test
        run: ./test.sh