# Jobs:
# - required: stable and beta rust toolchains on ubuntu
# - minimal: minimal versions of deps
# - os-check: stable on macos and windows

name: test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu-latest/rust-${{ matrix.toolchain }}
    strategy:
      matrix:
        # beta to test next version of toolchain
        toolchain: [stable, beta]
    steps:
      - name: git checkout din/master
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            deps/
          key: ${{ runner.os }}/rust-${{matrix.toolchain}}/cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust-${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Clone riscv gnu toolchain
        run: |
          mkdir -p deps
          git clone https://github.com/riscv/riscv-gnu-toolchain deps/riscv-gnu-toolchain
      - name: cargo build --release
        run: cargo build --release